Промежуточная аттестация

a.Импортируйте библиотеку NumPy

In [ ]:
import numpy as np

b.Создайте массив из 10 нулей

In [ ]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


c.Создать массив из 10 единиц

In [ ]:
array=np.ones(10)
print("An array of 10 ones:")
print(array)

An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


d.Создать массив из 10 пятерок

In [ ]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


e.Создать массив из целых чисел от 10 до 50

In [ ]:
array=np.arange(10,51)
print("Array of the integers from 10 to 50")
print(array)

Array of the integers from 10 to 50
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


f.Создать массив из четных чисел от 10 до 50

In [ ]:
array=np.arange(10,51,2)
print("Array of all the even integers from 10 to 50")
print(array)

Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


g.Создать матрицу 3х3 с числами от 0 до 8

In [ ]:
x = np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


h.Создать единичную матрицу 3x3

In [ ]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


i.Используйте NumPy для генерации случайного числа от 0 до 1

In [ ]:
rand_num = np.random.normal(0,1,1)
print("Random number between 0 and 1:")
print(rand_num)

Random number between 0 and 1:
[0.58979227]


j.Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения

In [ ]:
rand_num = np.random.normal(0,1,25)
print("25 random numbers from a standard normal distribution:")
print(rand_num)

25 random numbers from a standard normal distribution:
[ 0.71793939  0.24967442 -1.16409682  0.28572626  0.70889507  1.33984002
 -1.46939755  0.37970269  2.72984207 -1.72195235  0.91342323 -1.49897616
 -2.45439558 -0.11264484  0.90089259  0.88715321 -0.6845544  -1.01286067
  0.16742202  0.98685807  2.01293977  0.67805347  0.9223191  -1.5978262
 -0.99001212]


k.Создайте следующую матрицу используя функции библиотеки NumPy

In [ ]:
a=np.arange(0.01, 1.01, 0.01).reshape(10, 10)
print(a)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


l.Дана стартовая матрица (обязательно запустите код ниже в вашемрешении!). Эта матрица будет использоваться в последующих задачах

In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Необходимо написать код который вернет следующую матрицу из стартовой:

In [ ]:
mat=np.arange(1,26).reshape(5,5)
print(mat[2:5, 1:5])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


m. Написать код обращения к элементу который вернет значение  20 изстартовой матрицы задачи l

In [ ]:
mat=np.arange(1,26).reshape(5,5)
print(mat[3][4])

20


n.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже 

In [ ]:
mat=np.arange(1,26).reshape(5,5)
print(mat[0:3, 1:2])

[[ 2]
 [ 7]
 [12]]


o. Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже

In [ ]:
mat=np.arange(1,26).reshape(5,5)
print(mat[4, :])

[21 22 23 24 25]


p. Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже

In [ ]:
mat=np.arange(1,26).reshape(5,5)
print(mat[3:5, :])

[[16 17 18 19 20]
 [21 22 23 24 25]]


q.Получить сумму всех значений в стартовой матрице mat

In [ ]:
mat=np.arange(1,26).reshape(5,5)
print(mat.sum())

325


r. Получить стандартное отклонение в стартовой матрице mat

In [ ]:
mat=np.arange(1,26).reshape(5,5)
print(mat.std())

7.211102550927978


s.Получить сумму значений в колонках в стартовой матрице mat

In [ ]:
mat=np.arange(1,26).reshape(5,5)
print(mat)
print('__________________')
print(mat.sum(axis=0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
__________________
[55 60 65 70 75]
